DROP DATABASE IF EXISTS foodDb;
DROP USER IF EXISTS `foodDb`@`%`;
CREATE DATABASE IF NOT EXISTS foodDb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `foodDb`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
    CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `foodDb`.* TO `foodDb`@`%`;