export const listOfDbFoods = [
  "Barnemat, Sinlac spesialgrøt, pulver, Nestlé",
  "Cupcakes, med glasur, av pulver, smør",
  "Falafel, kikertboller, hjemmelaget",
  "Sau, fårekjøtt, lettsaltet, rå",
  "Karbonadedeig, storfe, rå",
  "Sodd, med kjøttboller, hermetisk",
  "Nøttestek",
  "Kjøttdeig, storfe, med salt og vann, rå",
  "Wasabirot, rå",
  "Solbærsirup, ublandet",
  "Tomat, norsk, rå",
  "Lettmelk, 1,0 % fett, Tine",
  "Karamell, med sjokoladetrekk",
  "Tzatziki",
  "Plantebasert grillpølse, solsikkeprotein, Go vegan",
  "Pasta, fullkorn, kokt med salt",
  "Sorbet",
  "Smoothie, ananas og ingefær",
  "Leverpostei, ovnsbakt, Gilde",
  "Kornblanding, med frukt og nøtter, Go'dag Energimüsli",
  "Kastanjer, ristede",
  "Rips, rå",
  "Smoothie, yoghurt, juice, banan og bær",
  "Fyrstekake, med epler",
  "Pasta med kalkun, ostesaus, fryst, kjøpt",
  "Banankake",
  "Lam, bogstek, rå",
  "Tilslørte bondepiker, med kavring",
  "Pigghå, håbrann, rå",
  "Sellerirot, rå",
  "Sesampostei/-pasta, tahini",
  "Tyttebærsyltetøy",
  "Hirse, hele korn",
  "Egg, stekt i fett",
  "Makrell, varmrøkt",
  "Brød, ekstra grovt (75-100 %), kjøpt, Grovt og godt havrebrød",
  "Blålange, rå",
  "Multi 0,65 g/stk, Nycoplus",
  "Brød, glutenfritt, grovt, med lettmelk, hjemmebakt",
  "Rundstykker, av pulver, grove, glutenfrie",
  "Tomatsuppe, med makaroni, av pulver",
  "Barnemat, middag, gulrot og potet, fra 4 mnd",
  "Fiskepinner, forfritert, stekt i myk margarin",
  "Krabbe, naturell, hermetisk",
  "Likør, 35 vol-% alkohol",
  "Eggesalat, majonessalat, 37 % fett",
  "Baguett, glutenfri, Semper",
  "Fiskesuppe, med mager fisk, fryst",
  "Muffins, med blåbær",
  "Nøtteblanding, orientalsk blanding",
  "Vafler, med fløte/rømme, uten egg",
  "Sjokolade, med kokosfyll, Bounty",
  "Plantebasert middagsdeig",
  "Nudler av ris, tørr",
  "Stilton, blåmuggost",
  "Multi Vitaminmikstur, Nycoplus",
  "Eplejuice, most",
  "Kjøleskapsgrøt, havregryn",
  "Smørkrem, med hard margarin",
  "Tunfisk, i olje, avrent, hermetisk",
  "Geléfrukt, Seigmenn",
  "Daddel, tørket",
  "Merian, tørket",
  "Havrebasert drikke, appelsin- og mangosmak",
  "Kakebunn, glutenfri, av pulver, Toro",
  "Svin, familieribbe, rå",
  "Egg, kokt",
  "Salatdressing, uten fett",
  "Butterdeig",
  "Physalis, rå",
  "Gudbrandsdalsost, brunost",
  "Tomat, importert, rå",
  "Potetsalat, med lettmajones, 40 % fett",
  "Vafler, glutenfrie, av pulver, Toro",
  "Sjysaus, av pulver",
  "Havsalt",
  "Cheddar, gulost",
  "Barnemat, hirsegrøt med eple og pære, fra 6 mnd, pulver, Holle",
  "Vaniljesaus, av pulver",
  "Brød, grovt (50-75 %), kjøpt, Norsk Fjellbrød",
  "Pepper, hvit",
  "Likør, 17 vol-% alkohol, fløtebasert",
  "Pære, importert, rå",
  "Blokkebær, mikkelsbær, rå",
  "Potetmel, potetstivelse",
  "Syltetøy, 60 % bær, 30 % sukker",
  "Selbu blå, blåmuggost",
  "Kjøttdeig, kylling, rå",
  "Brus, fruktjuice, med sukker, Solo, Mozell o.l.",
  "Lam, sadel, rå",
  "Uer, lettsaltet, rå",
  "Saft, 500 g sukker pr. l råsaft, ublandet",
  "Tranebær, rå",
  "Pannekaker, med skummet melk, stekt uten fett",
  "Helmelk, 4,1 % fett, økologisk",
  "Kjeks, søt, barnekjeks med sjokolade",
  "Ris, arborio, risottoris, tørr",
  "Kikerter, hermetiske",
  "Iskrem, yoghurtis",
  "Svin, bacon med svor, stekt",
  "Loff, fint brød (0-25 %), formstekt, kjøpt",
  "Hyse, kolje, rå",
  "Barnemat, middag, kjøttkaker og poteter, fra 12 mnd",
  "Karve, kummin, hel",
  "Peanøtter, saltet, Eldorado",
  "Pizza, med tomatsaus og ost",
  "Kjeks, søt, Gjende",
  "Pannekaker, med banan",
  "Litchi, rå",
  "Servelat, X-tra",
  "Fruktstang, fruktgodteri",
  "Fiskekaker, Lofoten",
  "Paprika, rød, rå",
  "Barnemat, middag, vegetargryte, fra 12 mnd",
  "Bernaisesaus, av pulver",
  "Fiskekaker, Coop",
  "Knekkebrød, rug, Husman Sport",
  "Pære, uspesifisert, rå",
  "Cheeseburger, med brød, dressing mv, kjøpt",
  "Kokosolje",
  "Purre, kokt",
  "Crème Fraîche, 35 % fett",
  "Plantebasert deig, erteprotein, Naturli",
  "Husholdningshvitt, flytende",
  "Brisling, i olje, avrent, hermetisk",
  "Sterkvin, søt, portvin, 20 vol-% alkohol",
  "Olivenolje, extra virgin, jomfruolje",
  "Mandelmel",
  "Sjokoladekake, med glasur",
  "Sitronsaft, flaske",
  "Scones, grov, glutenfri",
  "Sei, filet, melpanert, stekt i soyaolje",
  "Loff, vann, hjemmebakt",
  "Brød, glutenfritt, fint, med lettmelk, hjemmebakt",
  "Fiskefarse, mager fisk, rå",
  "Pasta, glutenfri, av ris og grønnsaker, tørr, Orgran tricolore",
  "Pistasjnøtter",
  "Pasjonsfrukt, rå",
  "Cortado, enkel, med soyabasert drikke",
  "Barnemat, God natt havregrøt naturell, fra 6 mnd, pulver, Nestlé",
  "Pommes frites, gatekjøkken",
  "Rødspette, fylt, forfritert, fryst",
  "Kveite, hellefisk, rå",
  "Hvit saus, av pulver",
  "Ostekake, med kjeksbunn",
  "Barnemat, middag, kjøttkaker i brun saus, fra 8 mnd",
  "Eggedosis",
  "Tunfisk, makrellstørje, rå",
  "Vafler, med egg og helmelk",
  "Røde bønner, tørre",
  "Mel, glutenfritt, Finax",
  "Kondensert melk, søtet",
  "Vitaminbjørner, 2,1 g/stk, Collett",
  "Kaffe, pulver, tilberedt",
  "Plantebasert grillpølse, grønnsaker og potet, Hoff",
  "Kjøttboller, svenske, Gilde",
  "Storfe, ytrefilet, stekt",
  "Eple, Rød aroma, rå",
  "Ingefær, malt",
  "Makrell i tomat, hermetisk",
  "Banan, rå",
  "Ørret, sjøørret, rå",
  "Nektarin, rå",
  "Rødspette, filet, kavringpanert, rå",
  "Brød, halvgrovt (25-50 %), kjøpt, Yoghurtbrød",
  "Nellik, malt",
  "Barnemat, middag, spagetti bolognese, fra 15 mnd",
  "Kyllingburger, med brød, dressing mv, kjøpt",
  "Reinsdyrskav, fryst, rå",
  "Gulrot, knaskegulrot, norsk, rå",
  "Egg, økologisk, stekt",
  "Safran, tørket",
  "Fruktpuré, med eple, banan og jordbær, HiPP",
  "Solbærsaft, 500 g sukker pr. l råsaft, ublandet",
  "Solsikkefrø",
  "Rosinbolle, kjøpt",
  "Bolle, med sjokoladebiter",
  "Svin, ytrefilet, rå",
  "Potetchips",
  "Fløtemysost, brunost",
  "Fiskekaker, Godehav",
  "Makrell i tomat, hermetisk, King Oscar",
  "Brus, Tonic water",
  "Kjøttboller, kalkun og kylling",
  "Eggekrem, vaniljekrem",
  "Margarin, Melange, uten salt og melk, folie",
  "Paprika- og kikertpålegg, Plantego",
  "Appelsin, rå",
  "Svin, kotelett, kam, svinekoteletter, inntil 5 mm fettrand, rå",
  "Ørret, oppdrett, skiver, melpanert, stekt i fett",
  "Loff, fint brød (0-25 %), kjøpt",
  "Spinat, rå",
  "Torsk, filet, kavringpanert, stekt i fett",
  "Grønnsaksblanding, blomkål, erter, gulrot, fryst",
  "Tørrfisk",
  "Sild, marinert, i majones/rømme",
  "Tykklefse, uten fyll",
  "Akkar, innbakt, forfritert, fryst",
  "Soyabasert drikke",
  "Rødspette, filet, melpanert, stekt i fett",
  "Kalkun, bryst, filet, uten skinn, rå",
  "Sjokoladepudding, Piano",
  "Couscous, kokt",
  "Rødbete, norsk, rå",
  "Mel, glutenfritt, Jyttemel Original",
  "Jordbærsyltetøy, rørt/fryst",
  "Lever, kylling, rå",
  "Lettmelk, 0,5 % fett, vitamin D, Tine",
  "Falukorv",
  "Matfett, Flott",
  "Kremfløte, 37 % fett, laktosefri",
  "Grytebasis, med ris, meksikansk, uten kjøtt",
  "Laks, oppdrett, skiver, kokt",
  "Pastiller, uten sukker",
  "Ananas, rå",
  "Brioche",
  "Caffe mocca",
  "Ørret, oppdrett, kokt",
  "Yoghurt, vanilje, 0 % fett, Yoplait",
  "Leverpostei, hermetisk",
  "Rødspette, panert, forfritert, fylt, ovnsstekt uten fett",
  "Skummet melk, Tine",
  "Psylliumfrø, loppefrø",
  "Brus, sitronsmak, med sukker",
  "Pinnekjøtt, råvare",
  "Byggryn, kokt",
  "Peanøtter, saltet, Polly",
  "Skinkerull, Westfalerskinke",
  "Brød, halvgrovt (25-50 %), kjøpt, Odelsbrød",
  "Sei, filet, kavringpanert, rå",
  "Pasta, grønn, fersk, rå",
  "Rosenkål, norsk, rå",
  "Nøttebunn",
  "Mais- og risflak, frokostblanding, glutenfri, special flakes, Semper",
  "Peanøttsmør",
  "Aspargessuppe, hjemmelaget",
  "Marsipankake, med syltetøy og krem",
  "Lutefisk, kokt",
  "Sjokolade, mørk, 70 % kakao",
  "Vann, drikkevann",
  "Vaniljesukker",
  "Vannkastanje, rå",
  "Sukker, hvitt",
  "Storfe, stek, roastbiff, rosa stekt",
  "Caffe latte, enkel, med helmelk",
  "Crème Chérie, mykost",
  "Medisterpølse, røkt/urøkt, kokt",
  "Eplecidereddik",
  "Potet- og purreløksuppe, hjemmelaget",
  "Potetchips, med mindre fett",
  "Kikerter, kokt",
  "Barnemat, havregrøt med banan og mango, fra 8 mnd, spiseklar, Nestlé",
  "Tyttebær, rå",
  "Taco med skjell, karbonadedeig, grønnsaker",
  "Muffins, med gulrot",
  "Fruktsuppe, av pulver",
  "Chevre, geitost, naturell",
  "Laksepålegg, med vårløk og sitron",
  "Blod, okse, rå",
  "Ørret, sjøørret, melpanert, stekt i fett",
  "Fersken, rå",
  "Kjeks, Kaptein",
  "Kaffehvitt, pulver, Coffeemate",
  "Risbasert drikke",
  "Laks, oppdrett, rå",
  "Plantebasert produkt, med samme bruksområde som ost, Go Vegan",
  "Cappucino, enkel, med laktosefri melk",
  "Wokblanding, thai",
  "Pasta, naturell, kokt",
  "Solsikkeolje",
  "Majones, ekstra lett, 25 % fett",
  "Kokosbollekake",
  "Kyllingpostei, ovnsbakt, Prior",
  "Paprika, gul/oransje, rå",
  "Kjøttpølse, med mindre fett",
  "Hønsefrikassé, hjemmelaget",
  "Tilskuddsblanding, fra 6 mnd, pulver",
  "Eggeplomme, rå",
  "Kantaloupemelon, rå",
  "Salt, bordsalt, jodert, Jozo",
  "Tran, Møllers",
  "Barnemat, fruktgrøt med pære og banan, fra 8 mnd, pulver, Nestlé",
  "Pizza, parma, hjemmelaget",
  "Sild, fetsild, sommersild, rå",
  "Sushi, maki, tempura",
  "Puffet hvete, med sukker og honning, Honni korn",
  "Kapers, hermetisk",
  "Kjøttboller, kylling, Coop",
  "Røye, stekt uten fett",
  "Plomme, rå",
  "Reker, innbakt, forfritert, stekt i soyaolje",
  "Popcorn, kjøpt",
  "Lettmelk, 1 % fett, uspesifisert",
  "Pavlova, med kremfløte og bær",
  "Gjær, tørrgjær",
  "Plantebasert pølse, soyaprotein, Hälsans kök",
  "Pannekaker, av pulver, Toro",
  "Kjeks, grov, Kornmo",
  "Vafler, med egg, lettmelk",
  "Fiskegryte, med torsk og tomat",
  "Karamellsaus",
  "Donuts, med sjokoladeglasur, kjøpt",
  "Morsmelkerstatning, fra fødsel, pulver",
  "Rismel",
  "Hvite kakemenn",
  "Mineralvann, uten kullsyre, Bonaqua naturell",
  "Reinsdyr, bog, stek, rå",
  "Kornblanding, 4-korn",
  "Kylling, lår (overlår og lårklubbe), uten skinn, ovnsstekt",
  "Fiskesuppe, med mager fisk, jevnet",
  "Kjøttkaker, Nordfjord",
  "Linfrøolje",
  "Akkar, tiarmet blekksprut, rå",
  "Steinbit, filet, melpanert, stekt i fett",
  "Helmelk, uspesifisert",
  "Knekkebrød, med ekstra fiber",
  "Sjokolade, fylt, konfekt",
  "Lam, fårikålkjøtt, rå",
  "Sopprotein, Quorn",
  "Amaranth, tørr",
  "Chili con carne",
  "Majones, lett, 40 % fett",
  "Oliven, grønne, med paprikafyll",
  "Betasuppe, hjemmelaget",
  "Gulrot, terninger, fryst",
  "Kremost, lett, Philadelphia",
  "Rugbrød, fint (0-25 %), kjøpt",
  "Havreflak, Havreflakes",
  "Kyllingpostei",
  "Fiskekarbonader, kjøpt",
  "Tacoskjell, Old El Paso",
  "Havrebasert drikke, med jod, kalsium, vitaminer (vit B2, folat, vit B12, vit D)",
  "Sjokolademelk, Sjokomelk",
  "Sandkake, småkake",
  "Pekannøtter",
  "Fårikål av lammekjøtt",
  "Estragon, tørket",
  "Hyllebær, rå",
  "Laks, filet, stekt i panne",
  "Galiamelon, rå",
  "Marengsbunn",
  "Yoghurt, jordbær, Tine",
  "Husholdningssaft, ublandet, kjøpt",
  "Salami",
  "Geitost, hvit, Balsfjord",
  "Appelsinjuice, fra konsentrat",
  "Appelsinjuice, ferskpresset",
  "Kjeks, søt, havre, Bixit",
  "Torsk, skiver, kokt",
  "Solbærsirup, drikkeklar",
  "Rugmel, sammalt",
  "Iskrem, med kjeks, sjokolade, nøtter",
  "Korianderfrø",
  "Mineralvann, med kullsyre, Bris naturell",
  "Blåbærsyltetøy, lett",
  "Grønnkål, fryst, rå",
  "Høne, kjøtt med skinn, kokt",
  "Pizza, Ristorante Speciale",
  "Sikorisalat, rå",
  "Plantebasert produkt, med samme bruksområde som ost, Coop",
  "Papaya, tørket",
  "Søtpotet, med skall, kokt uten salt",
  "Erter, fryst",
  "Pasjonsfruktjuice",
  "Kornblanding, med bær, Go'dag Blåbærmüsli",
  "Gjær, pressgjær",
  "Sashimi, tunfisk",
  "Hyrdepai, med kjøttdeig, grønnsaker og potetmos",
  "Bringebærsyltetøy, uten tilsatt sukker",
  "Syrnet melk, blåbær, laktosefri, Biola",
  "Grønnsaksblanding, kålrot, gulrot, sellerirot, rødløk, pastinakk, fryst",
  "Storfe, bogstek, rå",
  "Bønnespirer, mungbønnespirer, rå",
  "Leverpostei, hermetisk, Stabburet",
  "Kaviar, polarkaviar",
  "Lettmelk, 0,5 % fett, vitamin D, uspesifisert",
  "Kvarg, 7 % fett, Kesam",
  "Meterbønner, rå",
  "Frokostkorn, sjokoladesmak",
  "Riskrem",
  "Kruskakli, hvetekli, Regal",
  "Syrnet melk, jordbær, Biola",
  "Goudaost",
  "Neper, norsk, rå",
  "Brød, glutenfritt, grovt, med vann, hjemmebakt",
  "Østavind, gulost",
  "Adzukibønner, tørr",
  "Potetchips, Maarud",
  "Gressløk, rå",
  "Kjøttdeig, storfe, uten salt og vann, rå",
  "Brokkoli, uspesifisert, rå",
  "Gås, kjøtt med skinn, ovnsstekt",
  "Mineralvann, med kullsyre, Farris naturell",
  "Kaviar, av torskerogn",
  "Blodpudding",
  "Gresskar, hokkaido, rå",
  "Muffins, med sjokoladebiter",
  "Taco med tortilla, kjøttdeig, grønnsaker",
  "Hvitting, rå",
  "Svin, indrefilet, rå",
  "Kalv, stek, rå",
  "Svin, kjøtt fra knoke, rå",
  "Syrnet melk, Kulturmjølk",
  "Hasselnøtter",
  "Kalkun, kjøtt uten skinn, rå",
  "Kakaopulver",
  "Ribberull, skiver",
  "Krepsehale, i lake, avrent",
  "Brun saus, av blokk",
  "Sei, filet, melpanert, stekt i myk margarin",
  "Storfe, entrecôte, rå",
  "Geitmelk, langtidsholdbar",
  "Kjeks, søt, havre og sjokolade",
  "Steinsopp, rå",
  "Bremykt, mykere",
  "Norzola, blåmuggost",
  "Makrell i tomat, 60 % makrell, hermetisk, Stabburet",
  "Kylling, lårklubbe (underlår), uten skinn, rå",
  "Tofu, soyabønneprodukt",
  "Koriander, rå",
  "Fiskekarbonader, Godehav",
  "Makrell, juli-sept (fet), stekt i fett",
  "Kvæfjordkake, Verdens beste",
  "Plantebasert pølse, soyaprotein, Naturli",
  "Basilikum, rå",
  "Iskrem, med kjeks, Krone-is med jordbær",
  "Hvitløk, rå",
  "Lam, kotelett, stekt",
  "Wienersnitzel, rå",
  "Barnemat, middag, couscous og biff, fra 12 mnd",
  "Fiskesuppe, med laks, fryst",
  "Ingefær, syltet",
  "Tortilla, maislefse",
  "Peppernøtter",
  "Quinoa, hvit, tørr",
  "Havregrøt, med vann",
  "Peanøtter, saltet, Maarud",
  "Sukkerbrød",
  "Tomatsalsa",
  "Margarin, Olivero, beger",
  "Brød, grovt (50-75 %), kjøpt, First Price kneipp",
  "Hvetemel, økologisk",
  "Kjeks, søt, fylt med syltetøy el. frukt",
  "Puffet hvete, Hvetenøtter",
  "Quinoa, svart, tørr",
  "Risgrøt, med helmelk",
  "Chilinøtter, Polly",
  "Bønne- og olivensalat, Plantego",
  "Bidos, hjemmelaget",
  "Plantebasert burger, soyaprotein, Hälsans kök",
  "Stangselleri, norsk, rå",
  "Hvitvin, halvsøt/søt, inkl musserende",
  "Alfalfaspirer, rå",
  "Rognebær, rå",
  "Hare, kjøtt, rå",
  "Geitost, smørbar, dill, Snøfrisk",
  "Energidrikk, tilsatt taurin, koffein og B-vitaminer",
  "Sterkvin, søt, vermouth, 15 vol-% alkohol",
  "Maismel",
  "Wraps, glutenfri, Bfree",
  "Kjeks, søt, havre, SIBAS",
  "Sjokolademelk, av pulver og lettmelk",
  "Hvetekake",
  "Magerost, smørbar, 10 % fett",
  "Plantebasert grillpølse",
  "Elg, stek, ovnsstekt",
  "Ris, upolert, naturris, langkornet, kokt",
  "Rundstykke, mellomgrovt, med skummet melk, hjemmebakt",
  "Granateple, rå",
  "Karbonader, Prima",
  "Brød, 100 % sammalt mel, skummet melk, hjemmebakt",
  "Barnemat, fruktgrøt med pære og banan, fra 8 mnd, spiseklar, Nestlé",
  "Syltetøy, 40 % bær, 40 % sukker",
  "Jordbærsyltetøy",
  "Tunfisk, i olje, ikke avrent, hermetisk",
  "Sjokoladekake, med ostekrem, glutenfri",
  "Kylling, hel, uten skinn, ovnsstekt",
  "Ris, polert, langkornet, tørr",
  "Brød, 1/3 sammalt mel, skummet melk, hjemmebakt",
  "Tomat, hermetisk",
  "Øl, redusert energiinnhold, lavkarbo",
  "Mel, glutenfritt, grovt, Toro",
  "Tortilla, wraps/burrito, hvetemel",
  "Sild, storsild, vintersild, rå",
  "Rundstykke, fint, med skummet melk, hjemmebakt",
  "Leverpostei, grov, dansk, Stryhns",
  "Kiwi, rå",
  "Ris, villris, rå",
  "Omelett, stekt uten fett",
  "Aprikossyltetøy",
  "Kremost, Philadelphia",
  "Fiskepudding, fløtepudding",
  "Kinakål, norsk, rå",
  "Spinat, fryst, rå",
  "Lyr, rå",
  "Kompott, av frukt og bær",
  "Morsmelkerstatning, fra fødsel, drikkeklar",
  "Plantebasert deig, soyaprotein, Naturli",
  "Jordbær, 100 g sukker pr. kg bær, fryst",
  "Salat, gresk, med fetaost, oliven",
  "Svin, tynnribbe, med svor, rå",
  "Lettmelk, 1,2 % fett, økologisk",
  "Kylling, hel, uten skinn, rå",
  "Surkål, kjøpt",
  "Taco med skjell, plantebasert deig, grønnsaker",
  "Pizzafyllbasis, uten kjøtt",
  "Pepperoni, Peppes",
  "Havremakroner, kjøpt",
  "Sjokolade, melkesjokolade, porøs",
  "Syrnet melk, rødbete/eple/lime, Biola",
  "Knekkebrød, glutenfritt",
  "Taco kryddermix, Santa Maria",
  "Perlebygg",
  "Smør, usaltet",
  "And, kjøtt med skinn, rå",
  "Minestronesuppe, uten kjøtt, hjemmelaget",
  "Kokosmel",
  "Kornblanding, med frukt, AXA Fruktmüsli",
  "Reinsdyrpølse",
  "Pasta, glutenfri, spagetti, tørr, Semper",
  "Tomatsuppe, Rett i koppen",
  "Pumpernikkel, fullkornsbrød, ekstra grovt (75-100 %), kjøpt",
  "Mangold, sølvbete, rå",
  "Røye, melpanert, stekt i fett",
  "Pasta, glutenfri, kokt",
  "Pepperkaker",
  "Torsk, filet, kavringpanert, rå",
  "Grønnsaksblanding, blomkål, bønner, erter, gulrot, fryst",
  "Wraps, glutenfri, Schär",
  "Sei, rå",
  "Oliven, grønne, pickles",
  "Horn, fint, hjemmelaget",
  "Svin, 70 % skinke, 30 % flatbiff, strimlet, rå",
  "Syrnet melk, bringebær, Biola",
  "Kokosmelk, mager, hermetisk",
  "Gorgonzola, blåmuggost",
  "Grytebasis, med pasta, pulver",
  "Croissant, uten fyll, kjøpt",
  "Mineralsalt",
  "Havre- og mandelbasert drikke ",
  "Storfe, kjøtt, rå",
  "Cashewnøtter, saltet",
  "Muffins, med kakao, melisglasur",
  "Honning",
  "Potet, lagringspotet, kokt med skall",
  "Chilinøtter",
  "Bolle, glutenfri, med lettmelk, hjemmebakt",
  "Muffins, av pulver, med melisglasur, glutenfrie",
  "Rogn, torsk, kokt",
  "Ostepop",
  "Pannekaker, med lettmelk, stekt i hard margarin",
  "Pannekaker, med skummet melk, stekt i hard margarin",
  "Lakris, søt",
  "Sei, kokt",
  "Brød, grovt (50-75 %), kjøpt, Superbrød",
  "Fiskepinner, forfritert, stekt i matolje",
  "Quinoa, svart, kokt",
  "Kveite, filet, melpanert, stekt i fett",
  "Jarlsberg, gulost, lett",
  "Drue, uspesifisert, rå",
  "Lettmelk, 0,7 % fett, økologisk",
  "Kjeks, søt, barnekjeks",
  "Kaffemelk, 3,5 % fett",
  "Skorsonnerot, svartrot, rå",
  "Hamburger, enkel, med brød, dressing mv, kjøpt",
  "Dressing, majonestype, 55 % fett",
  "Storfe, ytrefilet, rå",
  "Urtesalt",
  "Muffins, med sitron, melisglasur",
  "Alaska pollock, rå",
  "Moreller, rå",
  "Jordbærsyltetøy, uten tilsatt sukker",
  "Kaffefløte, 10 % fett",
  "Avokado- og kikertpålegg, Plantego",
  "Brunost, uspesifisert",
  "Yoghurt, vanilje, laktosefri",
  "Sei, filet, melpanert, stekt i smør",
  "Teriyakisaus",
  "Purreløk, norsk, rå",
  "Fiskepinner, Findus",
  "Grillpølse, kalkun og kylling, Prior",
  "Leverpostei, fersk, Stabburet",
  "Erter, grønne, hermetisk, avrent",
  "Bringebærsyltetøy, lett",
  "Goro, småkake",
  "Pizza, kjøpt",
  "Lam, ytrefilet, rå",
  "Macchiato, enkel, med soyabasert drikke",
  "Rødspette, filet, kavringpanert, stekt i fett",
  "Plantebaserte middagsboller",
  "Makrell i tomat, 60 % makrell, hermetisk, First Price",
  "Pasta, grønn, fersk, kokt",
  "Geitost, brunost",
  "Breiflabb, rå",
  "Sei, panert, fryst, First Price",
  "Brosme, rå",
  "Knakkpølse",
  "Brus, Bitter lemon",
  "Ørret, sjøørret, kokt",
  "Shiitakesopp, rå",
  "Pizza, kjøttdeig, hjemmelaget",
  "Makrell, mai-juni, kokt",
  "Kjøttkaker med ertestuing, Fjordland",
  "Havregryn, lettkokte/store",
  "Kanelbolle, skillingsbolle, med vaniljekrem, melisglasur, kjøpt",
  "Gulrotkake",
  "Sitron, rå",
  "Italiensk salat, majonessalat, 37 % fett",
  "Horngjel, rå",
  "Leverpostei, ovnsbakt, Vita hjertego",
  "Smågodt, blandet, uten sjokolade",
  "Wienerbrød, med syltetøy, kjøpt",
  "Brød, halvgrovt (25-50 %), kjøpt, Kneippbrød",
  "Vafler, med egg og lettmelk, uten fett",
  "Salami, dansk, Tulip",
  "Rullekake, med smørkrem, kjøpt",
  "Sjokolade, Milky Way",
  "Sukker, brunt",
  "Rødspette, panert, forfritert, fylt, stekt i fett",
  "Kylling, filet, uten skinn, rå",
  "Kjeks, Start",
  "Egg, økologisk, rå",
  "Brød, grovt (50-75 %), kjøpt, Skibrød",
  "Kokosfett",
  "Chiapudding",
  "Rømmegrøt",
  "Kokt skinke",
  "Grillpølse",
  "Smuldrepai, med eple",
  "Sjalottløk, rå",
  "Blomkål/brokkolisuppe, Rett i koppen",
  "Nøttekake, myk",
  "Pasta, fullkorn, tørr",
  "Ris, hurtigris, kokt",
  "Fiskesuppe, Bergensk, pulver",
  "Rundstykker, fiber, glutenfrie, Hatting",
  "Soyamel, med mindre fett",
  "Selbu blå, blåmuggost, økologisk",
  "Bolle, uten rosiner, kjøpt",
  "Lam, indrefilet, rå",
  "Cider, søt, 4,5 vol-% alkohol",
  "Ris, grøtris, 5-25 min koketid, tørr",
  "Barnemat, havregrøt med banan og bringebær, fra 6 mnd, spiseklar, Nestlé",
  "Røye, rå",
  "Remulade",
  "Fløyelsgrøt",
  "Serinakaker",
  "Kalkun, brystfilet, uten skinn, ovnsstekt",
  "Tran, med limesmak, Biopharma",
  "Sushi, maki, kveite",
  "Brød, 25 % sammalt mel, vann, hjemmebakt",
  "Tortilla, burrito, hvetemel, Old El Paso",
  "Vannkastanjer, hermetiske",
  "Mel, havrebrødmiks, glutenfri, Toro",
  "Pølsebrød, fint, kjøpt",
  "Hvitvin, halvtørr, 10 vol-% alkohol",
  "Lever, lam, rå",
  "Fruktpuré, eple, med fersken og mango, HiPP",
  "Barnemat, middag, grønnsakslasagne, fra 12 mnd",
  "Syrnet melk, blåbær/bringebær, BioQ",
  "Sjokolade, med gelé og marsipan, Troika",
  "Taco med skjell, laks, grønnsaker",
  "Kylling, filet, stekt i fett",
  "Sild, storsild/vintersild, kokt",
  "Formkake, uten glasur, kjøpt",
  "Egg, rå",
  "Spisskål, rå",
  "Rundstykker, fine, glutenfrie, Hatting",
  "Kålrotstappe",
  "Margarin, Soft Flora lett",
  "Nøkkelost, lett",
  "Mozzarella, i lake, importert",
  "Havregryn, lettkokte, økologiske",
  "Potetlompe, potetlefse, kjøpt",
  "Brisling, i tomat, hermetisk",
  "Gulrotsuppe, hjemmelaget",
  "Morrpølse",
  "Brød, 50 % sammalt mel, vann, hjemmebakt",
  "Formkake, med glasur, kjøpt",
  "Svin, sideflesk, uten ben, rå",
  "Nøttepålegg, med mindre sukker, Nugatti",
  "Ris, upolert, naturris, langkornet, tørr",
  "Hvetekimolje",
  "Kornblanding, müsli med frukt, nøtter, søtet",
  "Cortado, enkel",
  "Rosenkål, kokt",
  "Magerost, smørbar, 7 % fett",
  "Timian, rå",
  "Kantarell, rå",
  "Mørkt øl, Bayer og juleøl, 4,5-4,7 vol-% alkohol",
  "Tindved, havtorn, rå",
  "Tempeh, soyabønneprodukt",
  "Ghee",
  "Kylling, lår (overlår og lårklubbe), med skinn, rå",
  "Skonrokk",
  "Laks, røkt",
  "Iskrem, med kjeks, Krone-is med sjokolade",
  "Brokkoli, norsk, rå",
  "Kakao, med lettmelk, tilberedt",
  "Ciabatta, glutenfri, Schär",
  "Waldorfsalat",
  "Tomater, soltørkede, tørr",
  "Linfrø, knuste",
  "Høne, bryst, filet, uten skinn, rå",
  "Baconpostei ",
  "Chilinøtter, Den lille nøttefabrikken",
  "Aprikos, hermetisk, med sukkerlake",
  "Svin, bogstek, kjøtt uten fettrand, rå",
  "Cappucino, enkel, med havrebasert drikke",
  "Kalv, koteletter, rå",
  "Lettmelk, 1,2 % fett, langtidsholdbar",
  "Kirsebær, rå",
  "Blåbærsyltetøy",
  "Skagenrøre, Skagensalat",
  "Makrell, mai-juni, stekt i fett",
  "Rundstykke, grovt, med skummet melk, hjemmebakt",
  "Pudding, mandelsmak, Piano",
  "Kylling, hel, med skinn, rå",
  "Cortado, enkel, med laktosefri melk",
  "Gulløl, 5,7 vol-% alkohol",
  "Leverpostei, ovnsbakt",
  "Norvegia, gulost, økologisk",
  "Kanelbolle, skillingsbolle, med sukkerstrø, kjøpt",
  "Helmelk, 3,5 % fett, Tine",
  "Fennikel, rå",
  "Muffins",
  "Havål, rå",
  "Salat nicoise",
  "Tykklefse, påsmurt, kjøpt",
  "Akkar, innbakt, forfritert, stekt i olje",
  "Raclette, ost",
  "Eple, importert, rå",
  "Lam, lår, stek, rå",
  "Grønnsaksblanding, erter, gulrot, mais, fryst",
  "Bulgurgryn, tørr",
  "Piggvar, rå",
  "Reddik, norsk, rå",
  "Storfe, entrecôte, stekt",
  "Hvetebrikker, Weetabix",
  "Scones, grove, med yoghurt",
  "Aioli",
  "Nashi, asiatisk pære, rå",
  "Sennep",
  "Saft, 1000 g sukker pr. l råsaft, drikkeklar",
  "Torsk, panert, forfritert, stekt i fett",
  "Taco med tortilla, karbonadedeig, grønnsaker",
  "Hvetemel, siktet",
  "Lam, grytekjøtt, rå",
  "Plantebasert burger",
  "Blåbærsyltetøy, rørt/fryst",
  "Flatbrød, hjemmebakt type, kjøpt",
  "Blomkål, norsk, fryst",
  "Yoghurt, naturell",
  "Fiskeburger, panert, med brød, ost, saus, kjøpt",
  "Grønnsaksblanding, aspargesbønner, minigulrot, minimais, fryst",
  "Svin, koteletter, kam uten fettrand, stekt",
  "Aubergine, rå",
  "Smør, meierismør, ekstra salt, Kviteseidsmør",
  "Fiskepudding",
  "Lam, flatbiff, rå",
  "Yoghurt, blåbær, 0 % fett, Yoplait",
  "Sjokoladeglasur",
  "Rabarbragrøt",
  "Stabburpølse",
  "Grapefruktjuice",
  "Quinoa, rød, tørr",
  "Muffins, med gulrot, melisglasur",
  "Fiskegrateng, Findus Familiens fiskegrateng",
  "Potetskruer, potetringer",
  "Svin, stek uten fettrand, ovnsstekt",
  "Gulrot, babygulrot, fryst",
  "Sjokolademousse",
  "Elg, ytterlår, stek, rå",
  "Makrell, juli-sept (fet), kokt",
  "Kremost, krydder",
  "Vafler, med egg og skummet melk",
  "Brennevin, 40 vol-% alkohol",
  "Pizza, Grandiosa kjøttdeig og løk",
  "Syrnet melk, naturell, Biola",
  "Ricotta, ferskost",
  "Fiken, rå",
  "Bringebærsyltetøy",
  "Corn flakes, glutenfri, Schär",
  "Yoghurt, naturell, laktosefri",
  "Rødbetsalat, majonessalat",
  "Kveite, hellefisk, skiver, røkt, rå",
  "Valnøttolje",
  "Svin, skinke, med knoke, rå",
  "Salatdressing, olje og eddik, fransk dressing",
  "Storfe, kjøtt, kokt",
  "Storfe, flatbiff, rå",
  "Seibiff, melpanert, med forstekt løk, kjøpt, stekt i fett",
  "Normanna, blåmuggost",
  "Espresso, enkel",
  "Brød, grovbakst, sammalt mel, hjemmebakt",
  "Tran, Møllers Dobbel, kapsler",
  "Lettmelk, 0,5 % fett, vitamin D, laktosefri",
  "Brokkoli, importert, rå",
  "Tomat, kokt",
  "Sjokoladefondant",
  "Gulrotkake, med ostekrem, kjøpt",
  "Kjeks, søt, kremfyll",
  "Betasuppe, av pulver, tilberedt",
  "Vin, alkoholsvak",
  "Ris, Jasmin, kokt",
  "Cashewnøtter, saltet, Den lille nøttefabrikken",
  "Fiken, tørket",
  "Klippfisk, saltet og tørket",
  "Torsk, filet, kokt",
  "Saft, uten tilsatt sukker, kunstig søtet, drikkeklar",
  "Leverpostei, uspesifisert",
  "Muffins, med banan",
  "Magerost, smørbar, 3 % fett",
  "Manchego, ost",
  "Krabbe, kokt",
  "Tomater, soltørkede, innlagte i olje, avrent",
  "Lefse, ferdig smurt, Vestlandslefsa",
  "Rullekake, med smørkrem av margarin",
  "Makrell, mai-juni, rå",
  "Kveite, hellefisk, uspesifisert, rå",
  "Omelett, stekt i fett",
  "Gresskar, butternut, rå",
  "Storfe, bankekjøtt, rå",
  "Baconost, smørbar",
  "Solbærsaft, 1000 g sukker pr. l råsaft, drikkeklar",
  "Rosiner",
  "Kylling- og kalkunpølse, med ost",
  "Iskrem, fløte, med ekstra sjokolade",
  "Wonton-ark",
  "Ghee, vegetabilsk",
  "Gamalost",
  "Corn flakes, søt, Frosties",
  "Carambola, stjernefrukt, rå",
  "Kjøttkaker, Gilde",
  "Taco med tortilla, laks, grønnsaker",
  "Vegetarburger, hjemmelaget",
  "Pepperrot, rå",
  "Knekkebrød, rug og speltkli, Sigdal helsprøtt",
  "Saltstenger",
  "Sjokoladekake, med glasur, kjøpt",
  "Lam, lår med mørbrad, rå",
  "Solbærsyltetøy",
  "Knekkebrød, havre",
  "Barnemat, God natt havregrøt naturell, fra 6 mnd, spiseklar, Nestlé",
  "Dessertvin, ekstra søt, musserende",
  "Vaniljekrem, med helmelk",
  "Balsamicoeddik",
  "Rådyr, kjøtt, rå",
  "Tortillachips, nachochips, Maarud Tortilla Cheese",
  "Gresskarsuppe, hjemmelaget",
  "Kylling, overlår (lår uten lårklubbe), uten skinn, rå",
  "Sushi, maki, California",
  "Yams, rå",
  "Iskrem, fløtebasert",
  "Hamburger, rå",
  "Eggeplomme, kokt",
  "Pytt i panne, stekte poteter med kjøtt og løk, fryst, kjøpt",
  "Lungemos, kjøpt",
  "Fennikelfrø",
  "Moussaka, med kjøttdeig",
  "Svartøyebønner, tørr",
  "Brønnkarse, rå",
  "Reinsdyr, kjøtt, røkt",
  "Lettrømme, 10 % fett",
  "Kokt laks med urtesaus, gulrot og poteter, Fjordland",
  "Leverpostei, ovnsbakt, Mills",
  "Tomat, hakket, tetrapak",
  "Kylling, lårklubbe (underlår), uten skinn, ovnsstekt",
  "Risboller, av puffet ris og sjokolade",
  "Kylling, overlår (lår uten lårklubbe), med skinn, rå",
  "Aronia, svartsurbær, rå",
  "Søtpotetsuppe, hjemmelaget",
  "Hjerte, rå",
  "Pizza, Take Away Meat Lover by Big One",
  "Olivenolje",
  "Kjøttboller",
  "Riskaker, usaltet",
  "Brød, ekstra grovt (75-100 %), kjøpt, Havrebrød",
  "Multesyltetøy",
  "Solbærsaft, 500 g sukker pr. l råsaft, drikkeklar",
  "Rødkål, kokt",
  "Jackfrukt, rå",
  "Sei, filet, melpanert, stekt i fett",
  "Rapidsalat, norsk, rå",
  "Pastiller",
  "Kremost, urter",
  "Avokado, rå",
  "Tomatsuppe, pulver",
  "Fiskepinner, forfritert, stekt i hard margarin",
  "Blomkålsuppe, av pulver",
  "Pasta med kjøttsaus, bolognese, fryst, kjøpt",
  "Hamburger, dobbel, med brød, dressing mv, kjøpt",
  "Potetmos, av pulver, uten melk",
  "Kalverull",
  "Hvetemel, sammalt, fint/grovt",
  "Soyaolje",
  "Cashewnøtter",
  "Grovbakstmel",
  "Kjøttboller, kalkun og kylling, Prior",
  "Bringebærsyltetøy, rørt/fryst",
  "Is, vegetabilsk fett, havrebasert, med smak",
  "Rognleverpostei, Svolvær-/Lofotpostei",
  "Ajvar, paprikasaus, hjemmelaget",
  "Brød, glutenfritt, fint, med vann, hjemmebakt",
  "Okra, rå",
  "Matlagingsfett, uspesifisert",
  "Tomatjuice",
  "Pepperoni",
  "Frokostkorn, sjokoladesmak, Nestlé Nesquick",
  "Hvite bønner, store, hermetiske",
  "Knekkebrød, glutenfritt, Superknäcke chia",
  "Basilikum, tørket",
  "Squashfrø, gresskarfrø",
  "Plantebaserte boller, soyaprotein, VegMe",
  "Oregano, tørket",
  "Erter, tørre",
  "Uer, rå",
  "Loff, fint brød (0-25 %), spiral, kjøpt",
  "Café au lait, med laktosefri melk",
  "Gulrot, uspesifisert, rå",
  "Macchiato, enkel",
  "Fruktpuré, med eple, fersken, blåbær og bringebær, HiPP",
  "Melisglasur",
  "Pizza, skinke, hjemmelaget",
  "Speltmel, siktet",
  "Plantebaserte boller, potet og linser, Hoff",
  "Barnemat, fullkornsgrøt med pære, eple og bringebær, fra 8 mnd, spiseklar, Småfolk",
  "Pepperoni, Gilde",
  "Lasagne, med kjøttdeig, fryst, kjøpt",
  "Kikerter, tørre",
  "Grytebasis, Stroganoff, uten kjøtt",
  "Kylling, hel, med skinn, ovnsstekt",
  "Tebriks, tebirkes",
  "Pasta bolognese",
  "Gås, kjøtt uten skinn, rå",
  "Sjokoladekake, med smørkrem, glutenfri",
  "Sushi, nigiri, kveite",
  "Ketchup, tomatketchup",
  "Muffins, med sjokoladebiter, melisglasur",
  "Bønnegryte, vegetarisk",
  "Rosmarin, rå",
  "Soyaprotein, teksturert",
  "Smoothie, ananas og mango",
  "Brød, 25 % sammalt mel, skummet melk, hjemmebakt",
  "Edamamebønner, soyabønner, fryst",
  "Daimkake",
  "Kjøleskapsgrøt, havregryn og chiafrø",
  "Rugmel, siktet",
  "Makrell, vill (høst), rå",
  "Gås, kjøtt uten skinn, ovnsstekt",
  "Ananasjuice",
  "Caffe latte, enkel, med laktosefri melk",
  "Potet, lagringspotet, rå",
  "Kalkun, kjøtt uten skinn, ovnsstekt",
  "Guacamole",
  "Buljongpulver",
  "Palmeolje",
  "Feta, ost med geitmelk",
  "Fiskeboller, kjølevare",
  "Viltsaus, av pulver",
  "Grillpølse, X-tra",
  "Norvegia, gulost, vellagret",
  "Smoothie, blåbær og bringebær",
  "Kylling, lår (overlår og lårklubbe), med skinn, ovnsstekt",
  "Laks, vill, rå",
  "Chiafrø, tørket",
  "Svin, stek, med fettrand, ovnsstekt",
  "Lettmelk, 1,0 % fett, laktoseredusert",
  "Torsk, lettsaltet, kokt",
  "Sitronterte",
  "Havreputer, Jippi Havreputer",
  "Uer, kokt",
  "Kokt skinke, Gilde",
  "Kylling, lår (overlår og lårklubbe), uten skinn, rå",
  "Marsipan, 50 % mandler",
  "Pasta, fersk med kjøtt og ost, tortellini, rå",
  "Grillpølse, Gilde",
  "Geitost, smørbar, kantarell, Snøfrisk",
  "Kirsebærsyltetøy",
  "Loff, skummet melk, hjemmebakt",
  "Dressing, majonestype, 15 % fett",
  "Cherimoya, rå",
  "Formkake, fet, dansk sandkake",
  "Rambutan, rå",
  "Barnemat, fullkornsgrøt med eksotiske frukter og müsli, fra 12 mnd, spiseklar, Nestlé",
  "Svin, nakkekoteletter, stekt",
  "Sjokolade, Snickers",
  "Fiskepinner, forfritert, stekt i smør",
  "Sushi, maki, laks",
  "Cheddarsaus",
  "Pils, 4,7 vol-% alkohol",
  "Brennesle, rå",
  "Barnemat, fruktgrøt med eple og banan, fra 6 mnd, spiseklar, Småfolk",
  "Torsk, oppdrett, rå",
  "Mascarpone, kremost",
  "Pannekaker, med lettmelk, stekt i myk margarin",
  "Sirupskake",
  "Wienerpølse, Gilde",
  "Dipsaus, sursøt barbequesaus",
  "Grapefrukt, rå",
  "Rogn, torsk, hermetisk, stekt i fett",
  "Drue, grønn, rå",
  "Kvarg, 1 % fett, Kesam",
  "Bankekjøtt, salt",
  "Ål, rå",
  "Knutekål, rå",
  "Grønnsaksblanding, blomkål, brokkoli, gulrot, sukkererter, fryst",
  "Lever, storfe, rå",
  "Sitronskall",
  "Peanøtter, saltet",
  "Flatbrød, kjøpt",
  "Pitabrød, fint, kjøpt",
  "Skumgodt, marshmallows",
  "Norvegia, gulost",
  "Yoghurt, vanilje",
  "Sjokolade, med mintfyll, After Eight",
  "Portobellosopp, rå",
  "Helmelk, 3,5 % fett, laktosefri",
  "Rundstykke, fint, halvstekt, kjøpt, stekt",
  "Lam, kotelett og sadel, kjøtt uten fettrand, rå",
  "Seilaks, i olje, avrent",
  "Svin, familieribbe, stekt",
  "Byggrynsgrøt",
  "Pinjekjerner",
  "Salami, Gilde spesialsalami",
  "Ris, hurtigris, tørr",
  "Sveitserost, gulost",
  "Kokt skinke, First Price",
  "Villsvin, kjøtt, rå",
  "Nypesuppe, av pulver",
  "Makrell, kaldrøkt",
  "Kokosmelk, hermetisk",
  "Søtpotet, ovnsstekt, uten fett",
  "Frityrolje",
  "Nøttepålegg, Nugatti",
  "Brus, cola, kunstig søtet, lett",
  "Saft, 1000 g sukker pr. l råsaft, ublandet",
  "Smør",
  "Sushi, nigiri, kamskjell",
  "Kanelbolle, skillingsbolle, hjemmebakt",
  "Havre, ristet, med frukt, olje, Crüsli",
  "Smoothie, appelsin, gulrot og ingefær",
  "Sei, pankopanert, fryst, Lerøy",
  "Formkake, med mindre fett",
  "Kakaosmør",
  "Bjørnebærsyltetøy",
  "Mozzarella, lett, norsk",
  "Wokblanding, kinesisk",
  "Gås, kjøtt med skinn, rå",
  "Milkshake, sjokoladesmak",
  "Plantebasert burger, potet og linser, Hoff",
  "Håbrann, rå",
  "Kardemomme, malt",
  "Yoghurt, naturell, økologisk",
  "Fiskegrateng, Enghav Fiskegrateng med makaroni",
  "Iskrem, lettis, med mindre sukker og fett",
  "Rundstykke, fint, med vann, hjemmebakt",
  "Lettøl, lett, 2,5 vol-% alkohol",
  "Havre- og bokhvetegrøt, glutenfri",
  "Reker, kokt",
  "Hvitløkspulver",
  "Spinatsuppe, hjemmelaget",
  "Knekkebrød, glutenfritt, laktosefri, sesam og havsalt, Wasa",
  "Potet, tidligpotet, med skall, Kypros, rå",
  "Kokosmasse, usøtet",
  "Ris, hurtigris, 1 % salt, kokt",
  "Aprikos, rå",
  "Ris, polert, parboiled, langkornet, kokt",
  "Soyabasert drikke, med kalsium og vitaminer (vit B2, vit B12, vit D), søtet",
  "Camembert, hvitmuggost",
  "Rapsolje, kaldpresset, Odelia",
  "Fiskekaker, kjøpt",
  "Svisker",
  "Sarah Bernhard-kake",
  "Prim, med jern, Sprett",
  "Quinoa, tørr",
  "Gulrot, kokt",
  "Iskrem, med kjeks, Lion King Size",
  "Tacosuppe, hjemmelaget",
  "Lasagne, med kjøttdeig",
  "Spekesild, utvannet",
  "Guava, rå",
  "Muffins, med melisglasur",
  "Appelsinskall, rå",
  "Floradix",
  "Grillpølse, Nordfjord",
  "Karbonader",
  "Laks, oppdrett, skiver, stekt i fett",
  "Svin, flatbiff, stekt",
  "Tilskuddsblanding, fra 6 mnd, drikkeklar",
  "Kaffehvitt",
  "Grønnkål, rå",
  "Mel, glutenfritt, grovt, Semper",
  "Tunfisk, i vann, avrent, hermetisk",
  "Maisolje",
  "Pepperoni, Grilstad",
  "Oliven, sorte, i olje, hermetisk",
  "Pizza, Big One New York Grilled Steak",
  "Barnemat, fullkornsgrøt med pære, eple og bringebær, fra 8 mnd, pulver, Småfolk",
  "Havrebasert drikke, med kalsium og vitaminer (vit D, vit B2, vit B12) ",
  "Kruskakli, hvetekli, Møllerens",
  "Bjørnebær, rå",
  "Kokosmakroner",
  "Grytebasis, med pasta, italiensk, uten kjøtt",
  "Åbor, abbor, rå",
  "Smoothie, ananas og kokos",
  "Traktkantarell, rå",
  "Persillerot, kokt",
  "Margarin, Vita Hjertego myk",
  "Salami, dansk, First Price",
  "Rødkål, rå",
  "Lange, rå",
  "Sashimi, laks",
  "Rundstykke, grovt, kjøpt",
  "Cappucino, enkel, med helmelk",
  "Plantebasert grillpølse, VegMe",
  "Eplepai",
  "Brød, ekstra grovt (75-100 %), karbohydratredusert, kjøpt, Fiber og frø",
  "Brød, 2/3 sammalt mel, vann, hjemmebakt",
  "Caffe latte, enkel, med lettmelk",
  "Ris, polert, parboiled, langkornet, tørr",
  "Kjøttboller, First Price",
  "Syrnet melk, Kefir, med smak, Q-meieriene",
  "Solbær, rå",
  "Smågodt, salte",
  "Seibiff, melpanert, med forstekt løk, fryst, kjøpt",
  "Kalkun, kjøtt med skinn, rå",
  "Rabarbra, rå",
  "Kaffe, traktet, kokt",
  "Paprika, grønn, rå",
  "Mandelbasert drikke",
  "Cappucino, enkel, med soyabasert drikke",
  "Nudler, med egg, tørr",
  "Macchiato, enkel, med laktosefri melk",
  "Pesto, grønn, hjemmelaget",
  "Løk, sprøstekt",
  "Rugbrød, grovt (50-75 %), kjøpt",
  "Kyllinggryte, med tomat, løk, sopp",
  "Eggerøre, stekt uten fett",
  "Steinbit, rå",
  "Ananas, hermetisk, med sukkerlake",
  "Barnemat, middag, couscous og laks, fra 15 mnd",
  "And, kjøtt uten skinn, rå",
  "Kjøttsuppe med grønnsaker og poteter, Fjordland",
  "Vitamineral, 0,55 g/stk, Vitaplex",
  "Pasta, naturell, fersk, kokt",
  "Dill, rå",
  "Prim, lett",
  "Tranebær, tørket, søtet",
  "Pizza, Stenovnsbakt Tradizionale Diavola",
  "Taco kryddermix, Old El Paso",
  "Mel, vaffelmiks, glutenfri, Toro",
  "Løksuppe, hjemmelaget",
  "Storfe, mørbrad, rå",
  "Frokostkorn, sjokoladesmak, Coco Pops Crunchers",
  "Ris, polert, Jasminris, tørr",
  "Tunfisk, i gele, hermetisk",
  "Aspargesbønner, rå",
  "Nype, rå",
  "Brød, glutenfritt, Semper formbrød",
  "Delfiakake",
  "Karbonadedeig, stekt uten fett",
  "Eplemos",
  "Brød, grovt (50-75 %), kjøpt, Istidbrød",
  "Kokosbolle",
  "Potetchips, Kims",
  "Rundstykke, grovt, med vann, hjemmebakt",
  "Plommesyltetøy",
  "Fruktpuré, med eple, jordbær, banan og blåbær, HiPP",
  "Barnemat, flerkornsgrøt med eple og pære, fra 12 mnd, spiseklar, Småfolk",
  "Pære, norsk, rå",
  "Sjokolade, melkesjokolade",
  "Papaya, rå",
  "Eggehvite, rå",
  "Plantebasert deig, soyaprotein, VegMe",
  "Sandefjordsmør",
  "Barnemat, fullkornsgrøt med eksotiske frukter og müsli, fra 12 mnd, pulver, Nestlé",
  "Brød, glutenfritt, grovt, soyabasert drikke med kalsium, hjemmebakt",
  "Cherrytomat, importert, rå",
  "Dill, tørket",
  "Lever, svin, rå",
  "Reinsdyr, kjøtt, tørket, rå",
  "Mozzarella, norsk",
  "Svin, midtribbe, med kam og svor, rå",
  "Lam, ribbe, side med ben, rå",
  "Fiskekarbonader, makrell",
  "Gulost, uspesifisert",
  "Vannbakkels, uten fyll",
  "Margarin, Melange, flytende",
  "Crabsticksalat, majonessalat, 25 % fett",
  "Bananchips",
  "Brød, grovt (50-75 %), kjøpt, Speltbrød",
  "Sukkererter, norsk, rå",
  "Sharon, kakifrukt, rå",
  "Grønnsaksblanding, blomkål, brokkoli, fryst",
  "Kalkunrull, krydderskinke",
  "Uer, lettsaltet, skiver, kokt",
  "Rødspette, filet, kokt",
  "Laks, filet, gravet",
  "Sitronfromasj",
  "Linser, røde/rosa, tørr",
  "Brokkoli, kokt",
  "Lam, lårstek med mørbrad, ovnsstekt",
  "Kokosnøtt, rå",
  "Majones, ekte",
  "Cashewnøttpålegg, hjemmelaget",
  "Storfe, fett fra storfekjøtt, rå",
  "Drue, blå, rå",
  "Tyttebærsyltetøy, rørt/fryst",
  "Kavring, søt, sukkerkavring",
  "Potet, tidligpotet, rå",
  "Nudler, uten egg, tørr",
  "Brød, grovt (50-75 %), kjøpt, Pågen kjernesunt brød",
  "Svarte bønner, hermetiske",
  "Kokebanan, melbanan, plantain, rå",
  "Lever, torsk, rå",
  "Pak-choi, bok choy, kål, rå",
  "Grytebasis, Jegergryte, uten kjøtt",
  "Bremykt",
  "Eplenektar",
  "Grillpølse, kalkun og kylling, Solvinge",
  "Potet, hermetisk, avrent",
  "Svin, bogstek, med fettrand, rå",
  "Sjokolade, kokesjokolade, mørk",
  "Tortillachips, nachochips, Santa Maria",
  "Paneer, ost",
  "Karamell",
  "Eggerøre, stekt i fett",
  "Barnemat, middag, fiskegrateng, fra 12 mnd",
  "Laks, filet, ovnsstekt",
  "Ris, polert, langkornet, kokt",
  "Fiskekaker, Fiskemannen",
  "Nypesuppe, pulver",
  "Nøkkelost",
  "Torsk, forfritert, fylt, fryst",
  "Potetmospulver, med melk",
  "Pasta, glutenfri, av mais og ris, tørr, Barilla",
  "Paprika, grønn, kokt",
  "Linser, grønne og brune, tørre",
  "Reker, innbakt, forfritert, fryst",
  "Sild, fetsild/sommersild, kokt",
  "Quinoa, rød, kokt",
  "Mandler, skåldet",
  "Cashewnøtter, saltet, Rema 1000",
  "Tamarind, rå",
  "Frokostkorn, Jippi Frokosttall",
  "Risgrøt, med lettmelk",
  "Iskrem, pinneis, Royal Mørk",
  "Scones, fin, glutenfri",
  "Syrnet melk, Skumma Kulturmjølk",
  "Bulgurgryn, kokt",
  "Energidrikk, tilsatt taurin, koffein og B-vitaminer, sukkerfri",
  "Blåkveite, rå/kaldrøkt",
  "Torsk, filet, melpanert, stekt i fett",
  "Fiskegrateng, med egg, ovnsstekt",
  "Strandsnegle, norsk",
  "Kjøttpølse, Nordfjord",
  "Granola, hjemmelaget",
  "Havrebasert drikke, med kalsium og vitamin D",
  "Spekeskinke, Strandaskinke, Grilstad",
  "Tortilla, wraps, hvetemel, Santa Maria",
  "Sushi, nigiri, scampi",
  "Timian, tørket",
  "Svin, fettrand, rå",
  "Soyabønner, tørre",
  "Kveite, hellefisk, oppdrett, rå",
  "Sorghum",
  "Pizzabunn, uten fyll",
  "Fiskeboller, avrent, hermetisk",
  "Tomatpuré",
  "Cappucino, enkel, med lettmelk",
  "Pasta, naturell, tørr",
  "Bakepulver",
  "Kassava, rå",
  "Kjeks, søt, havreflarn",
  "Stikkelsbær, rå",
  "Sanasol",
  "Kanel, malt",
  "Sennepsfrø",
  "Kylling, hel, med skinn, landkylling, rå",
  "Østerssopp, rå",
  "Tomatsuppe, av pulver",
  "Kjøttboller, hermetisk",
  "Rype, kjøtt, rå",
  "Brun saus, kjøttkakesaus, av pulver",
  "Matlagingsprodukt, whipping",
  "Havrebasert drikke, økologisk",
  "Hetvin, tørr, 15 vol-% alkohol",
  "Kreps, kokt",
  "Potetsalat, med seterrømme",
  "Karamellpudding, Piano",
  "Ridderost",
  "Vørterøl",
  "Agurk, norsk, rå",
  "Grønnsakspostei, Vita hjertego",
  "Parmesan, ost",
  "Jordbærsyltetøy, lett",
  "Peanøtter",
  "Salami, mager, Gilde",
  "Valmuefrø",
  "Høne, filet, kokt",
  "Wienerpølse, Finsbråten",
  "Grytebasis, med ris, pulver",
  "Svin, kotelett, kam, svinekotelett, uten fettrand, rå",
  "Tortillachips, nachochips",
  "Peanøttolje",
  "Hamburgerbrød, fint, kjøpt",
  "Vegetabilsk postei, Tartex",
  "Søtpotet, rå",
  "Klibrød, med hvetekli",
  "Ørret, oppdrett, rå",
  "Marsipan, 30 % mandler",
  "Smoothie, blåbær og eple",
  "Pultost, Løiten",
  "Havregrøt, med melk",
  "Brød, grovt (50-75 %), kjøpt, Josefinebrød",
  "Sild, kryddersild",
  "Torsk, panert, forfritert, fylt, ovnsstekt uten fett",
  "Lettmelk, 1,0 % fett, Q-meieriene",
  "Muffins, med banan, melisglasur",
  "Kjøttdeig, storfe, stekt uten fett",
  "Karamellpudding, hjemmelaget",
  "Brød, 75 % sammalt mel, vann, hjemmebakt",
  "Rundstykke, mellomgrovt, med vann, hjemmebakt",
  "Kalkun, kjøtt med skinn, ovnsstekt",
  "Gudbrandsdalsost, brunost, lett",
  "Rogn, torsk, rå",
  "Chili, rød, rå",
  "Brokkoli, fryst",
  "Falafel, kikertboller, Hälsans kök",
  "Fromasj, av pulver",
  "Sjokoladedrikk, Rett i koppen, drikkeklar",
  "Bolle, med lettmelk, hjemmebakt",
  "Fiskegrateng, kjøpt",
  "Te, grønn, tilberedt",
  "Café au lait, med havrebasert drikke",
  "Vegetarlasagne, hjemmelaget",
  "Svinestek med surkål og poteter, Fjordland",
  "Kjeks, søt, sjokoladebiter, cookies, store",
  "Napoleonskake",
  "Kremfløte, 37 % fett",
  "Pære, hermetisk, med egen saft",
  "Pomelo, rå",
  "Bambusskudd, hermetisk",
  "Chilipulver",
  "Sjokolade, med kjeks",
  "Brus, fruktjuice, kunstig søtet, lett, Solo light, Mozell light o.l.",
  "Rødvin, tørr",
  "Wienerpølse, X-tra",
  "Fruktpuré, med eple og banan, HiPP",
  "Baguette, grov, hjemmelaget",
  "Rekesalat, majonessalat, 35 % fett",
  "Seterrømme, 35 % fett",
  "Ostegrill, ostewiener",
  "Coleslaw, kremet salat ",
  "Kylling- og kalkunpølse, med mindre fett",
  "Smultringer",
  "Laurbærblad, tørket",
  "Blomkål, norsk, rå",
  "Brennevin, 60 vol-% alkohol",
  "Wienerpølse, kalkun og kylling, Prior",
  "Melkepålegg, med sukker, Hapå",
  "Mel, glutenfritt, lyst, Toro",
  "Høne, kjøtt med skinn, rå",
  "Eple, hermetisk",
  "Blåbær, amerikanske, rå",
  "Yoghurt, jordbær, Q-meieriene",
  "Brownies, med sjokoladeglasur, kjøpt",
  "Pizza, vegetar, hjemmelaget",
  "Svin, skinkestek, rå",
  "Bagels, hjemmelaget",
  "Biscotti",
  "Lettmelk, uspesifisert",
  "Brød, ekstra grovt (75-100 %), kjøpt, Grovbrød uten hele korn",
  "Syltetøy, 45 % bær, 25 % sukker",
  "Potet, lagringspotet, kokt uten skall, saltet vann",
  "Sirup",
  "Sjokolade, med mandelkrokan, Daim",
  "Østers, rå",
  "Sjokolade, Mars",
  "Pizza, Big One Classic",
  "Storfe, rundstek, rå",
  "Fiskekarbonader, sei",
  "Hvite bønner, tørre",
  "Ansjos, hermetisk",
  "Sildesalat, med potet",
  "Pepper, cayenne, rød",
  "Iste, Nestea",
  "Gjedde, rå",
  "Rødvin, uspesifisert",
  "Hvete, helkorn",
  "Havrekli",
  "Pizza, Ristorante Mozarella",
  "Reinsdyrkaker, hermetisk",
  "Lettmelk, 1,0 % fett, laktosefri",
  "Barnemat, fruktgrøt med eple og banan, fra 6 mnd, pulver, Småfolk",
  "Sushi, maki, tofu, vegetar",
  "Servelat, Folkets",
  "Brie, hvitmuggost",
  "Havrebasert drikke, sjokoladesmak, tilsatt kalsium og vitaminer",
  "Havrebasert drikke",
  "Fiskegrateng, Coop X-tra Fiskegrateng",
  "Wienerpølse",
  "Barnemat, grøt, med ris, mais og banan, fra 4 mnd, spiseklar, Nestlé",
  "Sei, filet, kavringpanert, stekt i fett",
  "Polarbrød, hvete",
  "Hvetekim",
  "Sild, røkt, bøkling",
  "Vafler, av pulver, Toro",
  "Bokhvetemel",
  "Brelett",
  "Smoothie, mango og gojibær",
  "Eddik, 7 %",
  "Barnemat, middag, kyllingboller og pasta, fra 12 mnd",
  "Pizza, Grandiosa Original",
  "Karbonader, X-tra",
  "Dressing, majonestype, 30 % fett",
  "Kidneybønner, røde, hermetiske",
  "Blåskjell, rå",
  "Teffmel",
  "Brød, grovt, glutenfritt, Fria",
  "Sjokolade, småsjokolader",
  "Margarin, myk",
  "Taco med tortilla, plantebasert deig, grønnsaker",
  "Sosisser, små pølser",
  "Grønnsaksrøre, med tomat, Ratatouille",
  "Tacoskjell",
  "Brød, halvgrovt (25-50 %), kjøpt",
  "Kjøttkaker",
  "Makrell i tomat, 70 % makrell, hermetisk, Stabburet",
  "Agurksalat",
  "Brød, glutenfritt, grovt, soyabasert drikke, hjemmebakt",
  "Blomkål, kokt",
  "Lammerull",
  "Rundstykke, grovt, halvstekt, kjøpt, stekt",
  "Bokhvete, hele korn",
  "Tacosaus",
  "Reker, i lake, avrent",
  "Limabønner, smørbønner, tørr",
  "Sjøtunge, rå",
  "Torsk, filet, ovnsstekt",
  "Matfløte, 18 % fett",
  "Torsk, panert, Findus Steketorsk",
  "Svin, sideflesk, lettsaltet, stekt",
  "Hval, kjøtt, rå",
  "Caffe latte, enkel, med havrebasert drikke",
  "Sjokoladesaus, kjøpt",
  "Soyapølse, hermetisk",
  "Barnemat, middag, gulrot, fra 4 mnd",
  "Gaffelbiter, sild, hermetisk",
  "Sei, panert, fryst, kjøpt",
  "Taffelost, tomat",
  "Syltetøy, uten tilsatt sukker",
  "Kransekake",
  "Margarin, Vita Pro aktiv",
  "Kjøttpudding, stekt",
  "Hodekål, rå",
  "Radicchio rosso, salat, rå",
  "Pai, med skinke og ost",
  "Jordbær, 250 g sukker pr. kg bær, fryst",
  "Ørret, filet, røkt",
  "Ris, grøtris, 1 times koketid, tørr",
  "Hummer, kokt",
  "Halloumi, ost",
  "Bolle, med helmelk, hjemmebakt",
  "Pannekaker, grove",
  "Gulrot, importert, rå",
  "Julekake",
  "Grønnsaksblanding, brokkoli, gulrot, minimais, fryst",
  "Ris, Basmati, kokt",
  "Breiflabb, filet, kokt",
  "Rogn, torsk, presset, hermetisk",
  "Chorizo, pølse",
  "Vafler, grove",
  "Multer, molter, rå",
  "Blåskjell, avrent, hermetisk",
  "Kaktusfiken, rå",
  "Brød, halvgrovt (25-50 %), kjøpt, Jegerbrød",
  "Syrnet, tyknet havreprodukt",
  "Multekrem",
  "Asparges, rå",
  "Muskat, malt",
  "Appelsinsaft, ublandet",
  "Pizza, plantebasert deig, hjemmelaget",
  "Sjokolade, hvit",
  "Storfe, høyrygg, rå",
  "Plantebasert deig, soyaprotein",
  "Cashewnøtter, saltet, Eldorado",
  "Bayonneskinke, kokt",
  "Likør, søt, 21 vol-% alkohol",
  "Fiskesuppe, Bergensk, av pulver",
  "Druejuice",
  "Margarin, Soft Spesial",
  "Cæsardressing",
  "Valnøtter",
  "Gulrot, norsk, rå",
  "Mel, glutenfritt, Finmix, Semper",
  "Laksepålegg, 70 % laks, i beger, Stabbur-Laks",
  "Iskaffe, cappuchino",
  "Baconcrisp",
  "Bondebønner, hestebønner, tørr",
  "Ris, polert, Basmatiris, tørr",
  "Hveteflak ristet, med hvetekli, All-bran Regular",
  "Hvitvin, tørr, 12 vol-% alkohol",
  "Kyllingpostei, hermetisk, Stabburet",
  "Gräddost",
  "Borlottibønner, tørr",
  "Fyrstekake, med mandler",
  "Margarin, hard",
  "Barnemat, middag, vegetarisk, fra 6 mnd",
  "Melis",
  "Roastbiff, skiver",
  "Eple, uspesifisert, rå",
  "Hjertesalat, rå",
  "Hetvin, søt, 17 vol-% alkohol",
  "Chayote, rå",
  "Mel, glutenfritt, Schär",
  "Sjampinjong, hermetisk, avrent",
  "Knekkebrød, lyst",
  "Sukkertøy, drops",
  "Sushi, maki, scampi",
  "Natron",
  "Gulasj, hjemmelaget",
  "Bønner, brune, kokt",
  "Muffins, med sjokoladebiter, kjøpt",
  "Iskrem, fløte, med sjokoladebiter",
  "Blåbærsyltetøy, uten tilsatt sukker",
  "Løk, gul/rød, norsk, rå",
  "Paranøtter",
  "Kjeks, søt, glutenfri, Choco chip cookies",
  "Muffins, av pulver, glutenfrie",
  "Sushi, maki, avokado, vegetar",
  "Husholdningssaft, drikkeklar",
  "Brød, 50 % sammalt mel, skummet melk, hjemmebakt",
  "Kjeks, søt, Mariekjeks",
  "Pannekaker, med helmelk, stekt i hard margarin",
  "Fersken, hermetisk, med egen saft",
  "Torsk, lettsaltet, rå",
  "Surimi, LobNobs",
  "Svin, flatbiff, rå",
  "Karripasta, curry paste",
  "Plantebasert produkt, med samme bruksområde som ost, revet, Go Vegan",
  "Plantebasert schnitzel, soya- og hveteprotein",
  "Torsk, panert, forfritert, ovnsstekt uten fett",
  "Iskrem, med kjeks, syltetøy, sjokolade",
  "Plantebasert deig, soyaprotein, Hälsans kök",
  "Pepper, sort",
  "Fårepølse",
  "Nudler av ris, kokt uten salt",
  "Krumkaker",
  "Muffins, med sitron",
  "Hyse, kolje, kokt",
  "Skumgodt, Ahlgrens biler",
  "Asparges, hermetisk, avrent",
  "Smoothie, mango og pasjonsfrukt",
  "Soyabasert drikke, med kalsium og vitaminer (vit B2, vit B12, vit D), usøtet",
  "Tropisk juice",
  "Laks, vill, kokt",
  "Suksessterte",
  "Sjokolademelk, Litago",
  "Fruktsmoothie, med eple, jordbær og banan, Nestlé",
  "Vannmelon, rå",
  "Barnemat, middag, biff stroganoff med pasta, fra 15 mnd",
  "Gurkemeie, malt",
  "Quinoa, kokt",
  "Geitost, smørbar, rødløk og timian, Snøfrisk",
  "Blomkålsuppe, hjemmelaget",
  "Kjeks, søt, grov, Digestive",
  "Maisstivelse",
  "Hvetekli, ristet, All-Bran plus",
  "Barnemat, middag, grønnsaksrisotto og kalkun, fra 12 mnd",
  "Rabarbrasyltetøy",
  "Persille, tørket",
  "Mazarin, kjøpt",
  "Eple, Granny Smith, Golden Delicious, rå",
  "Macadamianøtter",
  "Kongereke, rå",
  "Kylling, lårklubbe (underlår), med skinn, ovnsstekt",
  "Linser, grønne og brune, kokt",
  "Paprikapulver",
  "Knekkebrød, hjemmelaget",
  "Wienerbrød, med eggekrem",
  "Barnemat, middag, oksekjøtt og potet, fra 12 mnd",
  "Cortado, enkel, med havrebasert drikke",
  "Kakekrem, romsmak, Piano",
  "Medisterkaker, stekt",
  "Pasta, fersk med kjøtt, tortellini, rå",
  "Kjøttdeig, svin, stekt uten fett",
  "Brisling, rå",
  "Sashimi, kveite",
  "Barnemat, havregrøt med banan og mango, fra 8 mnd, pulver, Nestlé",
  "Svin, mørbrad, rå",
  "Roquefort, blåmuggost",
  "Koriander, tørket",
  "Okserull",
  "Formkake, marmor",
  "Rislunsj med jordbær",
  "Kikertmel",
  "Mandelpålegg, hjemmelaget",
  "Soyasaus",
  "Smørkrem, med smør",
  "Skyr, med smak, kunstig søtet",
  "Taco med tortilla, kylling, grønnsaker",
  "Hodekål, kokt",
  "Frokostkorn, ristet hvete og ris, Spesial K",
  "Linse- og bønnesalat, Plantego",
  "Fiskegrateng, med egg, ovnsstekt, kjøpt",
  "Helmelk, 4 % fett, Q-meieriene",
  "Tranebærjuice",
  "Knekkebrød, rug, med fyll, sandwich",
  "Torsk, i skiver, rå",
  "Kornblanding, med frukt, Go'dag Fruktmüsli",
  "Skolebrød, med melisglasur, eggekrem, kokos, kjøpt",
  "Høne, kjøtt uten skinn, rå",
  "Lotusrot, rå",
  "Sjokoladekake, uten glasur",
  "Muffins, med blåbær, kjøpt",
  "Vaniljesaus, Piano",
  "Mandelbasert drikke, med kalsium og vitaminer (vit B2, vit B12, vit E, vit D), usøtet",
  "Brød, ekstra grovt (75-100 %), kjøpt",
  "Müslibar, energibar, hjemmelaget",
  "Grønnsaksblanding, blomkål, gulrot, rosenkål, fryst",
  "Babymais, minimais, hermetisk",
  "Brød, grovt (50-75 %), kjøpt, Løvebrølbrød",
  "Kjøttpølse, Gilde",
  "Mandler",
  "Saftis, Lollipop",
  "Fruktpuré, med eple og pære, HiPP",
  "Bønnekarbonader, stekt i soyaolje",
  "Kanin, kjøtt, rå",
  "Edamer, gulost",
  "Knekkebrød, rug, Husman",
  "Sesamfrø, med skall",
  "Wokblanding, indisk",
  "Mango, tørket, søtet",
  "Rosmarin, tørket",
  "Muffins, med blåbær, melisglasur",
  "Pangasius, rå",
  "Potetchips, Sørlandschips",
  "Biff stroganoff",
  "Popcorn, poppet i soyaolje",
  "Fiskekarbonader, Berggren",
  "Pizza, vegan, hjemmelaget",
  "Artiskokk, rå",
  "Byggmel",
  "Taco med skjell, kylling, grønnsaker",
  "Gruyere, ost",
  "Margarin, Melange",
  "Majones, lett, 50 % fett",
  "Eplemos, lett",
  "Kjeks, søt, Ballerina",
  "Ingefærrot, rå",
  "Brus, cola, med sukker",
  "Eggehvite, kokt",
  "Taco med skjell, kjøttdeig, grønnsaker",
  "Blåbær, rå",
  "Barnemat, kveldsgrøt, med ris, pasta og gulrot, fra 6 mnd, pulver, Semper",
  "Lammefrikassé",
  "Servelat",
  "Grillpølse, mager, Gilde",
  "Fiskepinner, forfritert, stekt i fett",
  "Vårløk, rå",
  "Caffe latte, enkel, med soyabasert drikke",
  "Café au lait, med soyabasert drikke",
  "Iste, kunstig søtet, lett, Nestea",
  "Bladsalat, norsk, rå",
  "Rundstykke, fint, kjøpt",
  "Klementin, rå",
  "Café au lait",
  "Lettrømme, 18 % fett, økologisk",
  "Saft, 500 g sukker pr. l råsaft, drikkeklar",
  "Krydderkake",
  "Knekkebrød, rug, grovt",
  "Sjokoladepulver, uten melk",
  "Macchiato, enkel, med havrebasert drikke",
  "Squash, zucchini, rå",
  "Soyamel",
  "Kyllingskinn, rå",
  "Mineralvann, med kullsyre, Bonaqua naturell",
  "Nori, tørket tang",
  "Fiskegrateng, med egg og makaroni, ovnsstekt",
  "Kjøttfarse, rå",
  "Fleskepølse",
  "Sjokolademelk, uten tilsatt sukker, Litago Uten",
  "Lam, fett fra lammekjøtt, rå",
  "Svin, sideflesk, lettsaltet, rå",
  "Sjokolade, med nøtter",
  "Fruktsaus, av pulver",
  "Sukkerbrød, med eggekrem, bær, gele",
  "Lapskaus, lys, storfekjøtt",
  "Margarin, Vita Hjertego´ lett",
  "Lomre, rå",
  "Kumquat, rå",
  "Lussekatter",
  "Eplemos, uten tilsatt sukker",
  "Sylte",
  "Barnemat, middag, potet og brokkoli, fra 4 mnd",
  "Smoothie, juice, banan og bær",
  "Kjeks, søt, vaffel, fylt",
  "Plantebasert produkt, med samme bruksområde som ost",
  "Jarlsberg, gulost",
  "Vita Optimal olje",
  "Hyse, kolje, røkt, skiver, rå",
  "Sjokoladepulver, Rett i koppen",
  "Te, svart, tilberedt",
  "Hvitvin, rosé, musserende",
  "Sjokoladepudding, av pulver",
  "Panetter, med kylling og ost",
  "Bolle, med skummet melk, hjemmebakt",
  "Rødvin, 12 vol-% alkohol",
  "Sild, marinert, sennepssild",
  "Kylling, overlår (lår uten lårklubbe), med skinn, ovnsstekt",
  "Multesyltetøy, rørt/fryst",
  "Spekeskinke",
  "Fiskekarbonader, mager fisk",
  "Sjampinjong, rå",
  "Rullekake, med syltetøy",
  "Hummus",
  "Brød, 2/3 sammalt mel, skummet melk, hjemmebakt",
  "Sild, storsild/vintersild, melpanert, stekt i fett",
  "Berlinerbolle, kjøpt",
  "Vaniljekrem, Piano",
  "Feltsalat, rå",
  "Bouillabaisse, fransk fiskesuppe",
  "Miso, fermentert soyabønnepasta",
  "Cæsarsalat",
  "Grønnsaksgryte, med potet",
  "Kjøttdeig, svin, rå",
  "Torsk, vill, rå",
  "Syrnet havreprodukt til matlaging, 15 % fett",
  "Norvegia, gulost, fyldig",
  "Appelsinmarmelade",
  "Jordbær, rå",
  "Smuldrepai, med bær",
  "Fruktcocktail, hermetisk, med egen saft",
  "Kyllingnuggets, fritert, dagligvare",
  "Rødspette, rå",
  "Mango, tørket",
  "Kjeks, salt, fet, Ritz, Seltiner",
  "Barnemat, kveldsgrøt, med ris, pasta og gulrot, fra 6 mnd, spiseklar, Semper",
  "Smoothie, mango og appelsin",
  "Margarin, Soft Flora, original",
  "Grønnsaksblanding, blomkål, brokkoli, gulrot, fryst",
  "Riskaker, lettsaltet",
  "Torsk, panert, forfritert, fylt, stekt i fett",
  "Linser, grønne, hermetiske",
  "Horn, grov, hjemmelaget",
  "Lettmelk, 0,5 % fett, vitamin D, Q-meieriene",
  "Babyspinat, rå",
  "Fruktpuré, med fersken, mango og eple, HiPP",
  "Solbærsaft, 1000 g sukker pr. l råsaft, ublandet",
  "Kringle, gjærdeig, med tørket frukt",
  "Appelsinsaft, drikkeklar",
  "Couscous, tørr",
  "Fiskegryte, med sei, løk og paprikasaus",
  "Sushi, nigiri, laks",
  "Lam, kotelett og sadel, kjøtt med fettrand, rå",
  "Norvegia, gulost, lett",
  "Knekkebrød, Synnøve Grovkrisp sesamfrø og linfrø",
  "Løk, kokt",
  "Margarin, Soft Flora, folie",
  "Trollkrem",
  "Kokosbasert drikke, med kalsium og vitaminer (vit B12, vit D)",
  "Bløtkake, med krem, syltetøy",
  "Lakriskonfekt",
  "Quinoa, hvit, kokt",
  "Knekkebrød, Mesterbakeren Original",
  "Skyr, banan",
  "Kjøttbuljong, tilberedt",
  "Fiskepaté, mager fisk",
  "Sveler",
  "Salami, Grilstad jubelsalami",
  "Pære, hermetisk, med sukkerlake",
  "Innbakte pølser",
  "Seitan, av hvetegluten",
  "Plantebaserte boller, erteprotein, Naturli",
  "Fløtegratinerte poteter",
  "Brød, grovt (50-75 %), kjøpt",
  "Pommes frites, fryst",
  "Pizzaost, revet",
  "Rapsolje",
  "Tacoskjell, tubs, Santa Maria",
  "Hamburger, ekstra kjøtt, med brød, dressing mv, kjøpt",
  "Kålrot, kokt",
  "Multi Barn 1,1 g/stk, Nycoplus",
  "Storfe, indrefilet, rå",
  "Fiskekarbonader, Fiskemannen",
  "Saftis",
  "Filodeig",
  "Havreputer, Havrefras",
  "Dessert-topping på boks",
  "Eplekake",
  "Semulegrøt",
  "Havremel",
  "Puffet ris",
  "Port Salut, kittmodnet ost",
  "Kyllingnuggets, fritert, fastfood",
  "Barnemat, grøt, med ris, mais og banan, fra 4 mnd, pulver, Nestlé",
  "Rosenkål, fryst",
  "Kylling, filet, kokt",
  "Kylling, lårklubbe (underlår), med skinn, rå",
  "Eple, tørket",
  "Mais, fryst",
  "Svin, skinkestek med fettrand, uten svor, rå",
  "Wienerkringle, med mandelfyll",
  "Brun saus, med løk, av pulver",
  "Lever, rein, rå",
  "Focaccia",
  "Grytebasis, orientalsk, uten kjøtt",
  "Nypesyltetøy",
  "Sesamfrø, uten skall",
  "Chapatti, med sammalt mel",
  "Brød, ekstra grovt (75-100 %), kjøpt, Grovt & Godt Grovbrød",
  "Kamskjell, rå",
  "Sjokoladepålegg, med mindre sukker, Sjokade",
  "Endivesalat, rå",
  "Puffet havre, Havrenøtter",
  "Karbonader, First Price",
  "Marsipanbrød, med sjokoladetrekk",
  "Mineralvann, med kullsyre, Olden",
  "Steinbit, kokt",
  "Sushi, maki, mango, vegetar",
  "Mango, rå",
  "Gomme, Namdal",
  "Pastinakk, rå",
  "Chilisaus, søt",
  "Skate, rå",
  "Fiskekarbonader, sild",
  "Persille, norsk, rå",
  "Mineralvann, uten kullsyre, Olden",
  "Taco kryddermix",
  "Potet, høstpotet, rå",
  "Jalapeño, rå",
  "Knekkebrød, rug, tynt, Rugsprø, Finncrisp",
  "Sesamolje",
  "Aprikos, tørket",
  "Paprika, rød, kokt",
  "Frokostsalat, majonessalat, med ostemasse",
  "Torsk, filet, stekt i panne",
  "Pizza, karbonadedeig, hjemmelaget",
  "Kremost, pepper",
  "Tacosaus, medium, Old El Paso",
  "Kaviarmix",
  "Sterkøl, bokkøl, 6,5 vol-% alkohol",
  "Rype, kjøtt, ovnsstekt",
  "Fiskekarbonader, laks",
  "Geitost, hvit, Kvitlin",
  "Brokkolisuppe, hjemmelaget",
  "Sirupssnipper, småkake",
  "Gelé, av pulver",
  "Svin, koteletter, kam med fettrand, stekt",
  "Grillpølse, kalkun og kylling",
  "Brune bønner, tørre",
  "Barnemat, Sinlac spesialgrøt, spiseklar, Nestlé",
  "Ris, villris, kokt",
  "Mangosalsa, hjemmelaget",
  "Tomatbønner, hvite bønner, i tomatsaus, hermetisk",
  "Kaviar, av lodderogn",
  "Kjøttboller, svenske, Coop",
  "Pasta, naturell, fersk, rå",
  "Krem, pisket, på boks",
  "Barnemat, flerkornsgrøt med eple og pære, fra 12 mnd, pulver, Småfolk",
  "Perlespelt",
  "Potetsalat, med lettrømme",
  "Servelat, mager, Gilde",
  "Hyse, kolje, røkt, skiver, kokt",
  "Chili, grønn, rå",
  "Muffins, med kakao",
  "Potetmos, potetstappe, hjemmelaget",
  "Yoghurt, med müsli og skogsbær, Go Morgen",
  "Kjeks, salt, glutenfri, Salti",
  "Mais- og risflak, frokostblanding, glutenfri, Schär",
  "Jordskokk, rå",
  "Marengs",
  "Fiskepaté, laks",
  "Krekling, krøkebær, rå",
  "Salsiccia, italiensk pølse",
  "Tacosaus, medium, Santa Maria",
  "Sushi, maki, tunfisk",
  "Popcorn, mikrobølgeovn",
  "Fiskegrateng, First Price Fiskegrateng med makaroni",
  "Sild, fetsild/sommersild, melpanert, stekt i fett",
  "Nudler, glass, tørr",
  "Berlinerkrans, småkake",
  "Flatbrød, havre, kjøpt",
  "Svin, grillben, rå",
  "Lettmelk, kakao, vitamin D",
  "Pultost, Hedemark",
  "Romanosalat, rå",
  "Agurker, syltede",
  "Karbonader, okse, rå",
  "Sushi, nigiri, tunfisk",
  "Corn flakes, Kelloggs",
  "Smoothie, guava og gojibær",
  "Barnemat, middag, fullkornspasta med grønnsaker, fra 12 mnd",
  "Kjeks, fet, Cream cracker",
  "Barnemat, middag, fullkornslasagne, fra 12 mnd",
  "Chilinøtter, Eldorado",
  "Lettrømme, 18 % fett",
  "Rødbeter, syltede",
  "Barnemat, havregrøt med banan og bringebær, fra 6 mnd, pulver, Nestlé",
  "Wienerpølse, mager, Gilde",
  "Babygulrot, importert, rå",
  "Krabbepinner, crabsticks, fryst",
  "Kremost, naturell",
  "Kjøttpølse",
  "Bernaisesaus, hjemmelaget",
  "Svin, nakkekoteletter, rå",
  "Margarin, Vita Hjertego´, flytende",
  "Kjeks, søt, sjokoladebiter, nøtter, cookies, små",
  "Anisfrø",
  "Svin, bacon med svor, rå",
  "Kalkunfilet, naturell/røkt",
  "Matlagingsprodukt, av havre, 13 % fett",
  "Fenalår",
  "Fiskesuppe, med mager fisk",
  "Syrnet melk, økologisk, Kefir, Tine",
  "Sennepssaus",
  "Paradisepler, rå",
  "Gelatin, plater/pulver",
  "Bringebær, rå",
  "Pizza, pepperoni, hjemmelaget",
  "Ris, hurtigris, 1 % salt, tørr",
  "Rømmedressing, med urter",
  "Karbonader, Gilde",
  "Kokt skinke, Nordfjord",
  "Plomme, hermetisk, med sukkerlake",
  "Eple, Ingrid Marie, rå",
  "Popcorn, uten fett",
  "Smoothie, bringebær og jordbær",
  "Lutefisk, tørr vare, rå",
  "Vin, alkoholfri",
  "Mais, norsk, rå",
  "Sjokolade, kokesjokolade, lys",
  "Kålrot, kålrabi, norsk, rå",
  "Salt, bordsalt",
  "Egg, økologisk, kokt",
  "Syrnet melk, blåbær, mager, Biola",
  "Brus, sitronsmak, kunstig søtet, lett",
  "Kabaret, med fiskepudding og reker",
  "Aspargesbønner, fryst",
  "Spekeskinke, Gilde",
  "Snickerskake",
  "Wokblanding, klassisk",
  "Pizzasnurrer",
  "Kakemiks, fin, glutenfri, pulver, Toro",
  "Løksuppe, gratinert med ost og brød, hjemmelaget",
  "Oreokake, av pulver, fløte og smør",
  "Mor Monsen, kake",
  "Kveite, skiver, kokt",
  "Snegler, hermetisk",
  "Kamskjell, kokt",
  "Honningmelon, rå",
  "Mungbønner, tørre",
  "Ruccolasalat, rå",
  "Fruktcocktail, hermetisk, med sukkerlake",
  "Scones, grove, med melk",
  "Vørterkake",
  "Servelat, Nordfjord",
  "Semulegryn, hvetegryn",
  "Geitost, smørbar, naturell, Snøfrisk",
  "Havreringer, Nestlé Cheerios",
  "Knekkebrød, rug, Ryvita",
  "Panna cotta",
  "Gresskar, rå",
  "Pistasjnøtter, saltet",
  "Jordskokksuppe, hjemmelaget",
  "Brune pinner",
  "Karri, malt",
  "Hollandaisesaus, hjemmelaget",
  "Plantebasert deig, soyaprotein og hvete, Folkets",
  "Matlagingsprodukt, av soya, 17 % fett",
  "Torsk, uspesifisert, rå",
  "Pesto, grønn, kjøpt",
  "Ertestuing, av pulver",
  "Medisterdeig, rå",
  "Ananas, hermetisk, med egen saft",
  "Mais, hermetisk",
  "Persillerot, norsk, rå",
  "Nudler, kokt, med krydder",
  "Plantebasert pølse, soyaprotein",
  "And, kjøtt uten skinn, ovnsstekt",
  "Øl, alkoholfritt",
  "Ananas, tørket",
  "Prim",
  "And, kjøtt med skinn, ovnsstekt",
  "Hjort, stek, rå",
  "Ål, røkt",
  "Byggryn",
  "Lime, rå",
  "Tomat, uspesifisert, rå",
  "Rabarbrasuppe",
  "Barnemat, hirsegrøt med eple og pære, fra 6 mnd, spiseklar, Holle",
  "Eple, norsk, uspesifisert, rå",
  "Cottage Cheese",
  "Rødbete, kokt",
  "Sei, filet, melpanert, stekt i hard margarin",
  "Brød, 1/3 sammalt mel, vann, hjemmebakt",
  "Kylling, hel, med skinn, landkylling, ovnsstekt",
  "Melk, uspesifisert",
  "Fløtemysost, brunost, lett",
  "Terte, uten fyll",
  "Tyggegummi, med sukker",
  "Fersken, hermetisk, med sukkerlake",
  "Svinekam, røkt",
  "Skyr, bringebær",
  "Sild, sursild, innlagt, avrent",
  "Sjokoladepålegg, Sjokade",
  "Pasta, fersk med ost, ravioli, rå",
  "Akkar, tiarmet blekksprut, kokt",
  "Fruktmüsli, frokostblanding, glutenfri, Finax",
  "Brød, 75 % sammalt mel, skummet melk, hjemmebakt",
  "Loff, fint brød (0-25 %), halvstekt, stekt",
  "Isbergsalat, issalat, rå",
  "Bogskinke, hermetisk",
  "Skummet melk, Styrk",
  "Kylling, overlår (lår uten lårklubbe), uten skinn, ovnsstekt",
  "Linser, røde, hermetiske",
  "Potetsalat, med ekte majones",
  "Sik, rå",
];
